### ISSUE TITLE
ghc 8.4.1 support

### ISSUE THREAD

**Issue by peti** [xmonad/xmonad#155]
xmonad-0.13 does not compile with ghc 8.4.1:

~~~
src/XMonad/Core.hs:155:10: error:
    • Could not deduce (Semigroup (X a))
        arising from the superclasses of an instance declaration
      from the context: Monoid a
        bound by the instance declaration at src/XMonad/Core.hs:155:10-35
    • In the instance declaration for ‘Monoid (X a)’
    |
155 | instance (Monoid a) => Monoid (X a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/XMonad/Core.hs:169:10: error:
    • Could not deduce (Semigroup (Query a))
        arising from the superclasses of an instance declaration
      from the context: Monoid a
        bound by the instance declaration at src/XMonad/Core.hs:169:10-37
    • In the instance declaration for ‘Monoid (Query a)’
    |
169 | instance Monoid a => Monoid (Query a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

**Comment by peti** [comment]
Ping?

**Comment by peti** [comment]
Maybe https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid is helpful?

**Comment by MichielDerhaeg** [comment]
This has been addressed by #153 and can be closed.

**Comment by gbaz** [comment]
It would be nice to get a new release that incorporates this fix

**Comment by byorgey** [comment]
I'm kind of the only xmonad developer still active who would be able to put out a new release right now, but it's not a priority for me and I'll be gone on vacation for the rest of the week.  I'll try to get around to this next week.

**Comment by fnurglewitz** [comment]
@byorgey don't worry, take your time :)

Thank you for your work, have fun on vacation :)

**Comment by psibi** [comment]
@byorgey Gentle reminder for a new release.

Thanks for all your work in this.

**Comment by colonelpanic8** [comment]
@byorgey Don't xmonad and xmonad-contrib typically get released together?

If so, would be nice to do something about

https://github.com/xmonad/xmonad-contrib/issues/268

for the new release right?

**Comment by peti** [comment]
Ping?

**Comment by peti** [comment]
@byorgey, if you don't mind giving me (http://hackage.haskell.org/user/PeterSimons) access to this project on Hackage, then I'd be happy to upload a release for you that fixes this issue. I'd also be happy to make the necessary changes in this Git repository to add support for new compilers versions about  to come out, when necessary, if you'll give me push access. I'm not much of an xmonad hacker, so I'd hesitate to say that I'd be able to maintain it, but I can certainly merge PRs, fix compiler issues, and upload release archives.

**Comment by psibi** [comment]
CC: @byorgey @pjones 

I also volunteer myself to do housekeeping for Xmonad. I currently maintain xmonad-extras and have previously contributed to xmonad-contrib. My Hackage id: https://hackage.haskell.org/user/psibi

**Comment by byorgey** [comment]
Hi all, my sincere apologies for not responding sooner.  I do still intend to be involved with xmonad, but it is just very far down on my priority list. Thanks also for the offers of help!  I have given @peti and @psibi push access to the xmonad repos, and also given @peti upload permissions on Hackage.

**Comment by LSLeary** [comment]
BTW contrib has some changes that need to be dealt with before it can get its own 0.14 release. I'm going to try to fast track them through, just check with me to make sure they're done before it goes on hackage.

**Comment by peti** [comment]
https://hackage.haskell.org/package/xmonad-0.14

**Comment by LSLeary** [comment]
xmonad/xmonad-contrib#275
